name: presence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter: 
    sdk: flutter
  get_cli: ^1.8.1
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  firebase_storage: ^11.6.10
  cloud_firestore: ^4.15.9
  image_picker: ^1.0.7
  convex_bottom_bar: ^3.2.0
  intl: ^0.19.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  syncfusion_flutter_datepicker: ^25.1.35

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/presence_white.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"


dev_dependencies: 
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  
  assets: 
    - assets/images/2.png
    - assets/images/3.png
  fonts: 
    - family: SometypeMono
      fonts: 
        - asset: assets/fonts/B612Mono-Bold.ttf
        - asset: assets/fonts/B612Mono-BoldItalic.ttf
        - asset: assets/fonts/B612Mono-Italic.ttf
        - asset: assets/fonts/B612Mono-Regular.ttf
        - asset: assets/fonts/MadimiOne-Regular.ttf

